### ISSUE TITLE
Crash in iOS 15 Beta

### ISSUE THREAD

**Issue by hardiktgreydesk** [AgoraIO-Community/Agora-iOS-Swift-Example#4]
Hello Team, 

We Implement agora SKD in one of our application. And recently we face crash issue in that in which device has Beta version 15.  

We get this crash report in crash analytics

AgoraCore
ahpl_xdump_detach + 27928

Please help in this if possible.

Thanks

**Comment by maxxfrazer** [comment]
Hi @hardiktgreydesk, this is either an issue with the iOS Beta that needs fixing by Apple, or a change that means we need to change the implementation of the Agora SDK.

I'd encourage you to create a ticket on [our support page](https://agora-ticket.agora.io), where the appropriate engineers can see this issue and get back to you on any progress.

Thanks!
