### ISSUE TITLE
Don't understand how to get the demo started

### ISSUE THREAD

**Issue by waldruupi** [AgoraIO-Community/Agora-iOS-Swift-Example#7]
![image](https://user-images.githubusercontent.com/28662355/130503767-2bf329b2-508c-45e7-af9e-c015e631b599.png)

I followed the repo guidelines and the curl command `curl 'http://localhost:8080/rtc/liveshopping/publisher/uid/0/'`

With this output: `{"rtcToken":"006889f88217a1f4cd289097b70a526e861IADCZH8gPyE04wmNFAKzKVHAVlQQgMIxTfYKpM62+ZyFKD9V0A4AAAAAIgCSBUcFtEMlYQQAAQBEACRhAgBEACRhAwBEACRhBABEACRh"}`

The server is run with this: `docker run -p 8080:8080 agora-token-service`

The AppID and App Certificate I double checked. 

In the SWIFT app, I changed the placeholders to this:

```
static let channelName: String = "liveshopping"
static let appId: String = "889f88217a1f4cd289097b70a526e861"
static var channelToken: String? = ""

    static var tokenBaseURL: String? = "006889f88217a1f4cd289097b70a526e861IAD/YVi91qrhg+Ruxotipkyzj3SgYj+8ZGP8Hk3ufEeUgD9V0A4AAAAAIgDDmZQA7z0lYQQAAQB/+iNhAgB/+iNhAwB/+iNhBAB/+iNh"
```

What am I doing wrong?

**Comment by maxxfrazer** [comment]
Hi! So what you have there (006889...) is the channel token, not the token URL. the URL is a URL path to the token server. In case you don't know, it's valid for 60 seconds by default, so watch out for the expiry there.

Alternatively, you could find your local computer's IP address on the network and add that as the token base URL, it would be something like this: `http://192.168.1.x:8080`. But check that from another computer or by going to the full URL on your test device.

**Comment by waldruupi** [comment]
Ahhh, got it got it. 
I was confused with naming of the variables, honestly it's more clear if it's just `token` and `url`, and have comments 

1. If I'm running the container on a localhost, then I should use an IP correct? 

But I got it to work with a Cloud Run instance.
